services:
  backend-php:
    container_name: backend-php
    build: ./docker/php
    working_dir: /app
    volumes:
      - ./Backend/PHP/Boilerplate:/app

  backend-db:
    container_name: backend-db
    image: postgres:18
    environment:
      POSTGRES_DB: fleet
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro

  algo-php:
    container_name: algo-php
    build: ./docker/php
    working_dir: /app
    volumes:
      - ./Algo:/app

volumes:
  db_data: